# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    
    ]
