# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190309_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
