# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
