# Generated by Django 2.1.2 on 2018-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedfiles_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='fileHash',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
