# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190104_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
